# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0004_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
