# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0005_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='client_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
