# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0006_contact_client_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='project_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
