# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0007_contact_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
