# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0008_auto_20170727_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='info_requested',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='today_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='client_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='client_signature',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='rfi',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_signature',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
