# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0009_auto_20170731_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client_signature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_signature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
