# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0009_auto_20170731_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='website',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='contact',
            name='client_signature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_signature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
